// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIsUXIz3qf-vqGLNquF_iYJIwkrDxRItc',
    appId: '1:214009413589:web:79709cd041bfaf8bdcc75c',
    messagingSenderId: '214009413589',
    projectId: 'bukanlibrarymws',
    authDomain: 'bukanlibrarymws.firebaseapp.com',
    storageBucket: 'bukanlibrarymws.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpubSPk1UqiU787OJNB4z7_SErz2VZn4c',
    appId: '1:214009413589:android:7bdd428bae49910edcc75c',
    messagingSenderId: '214009413589',
    projectId: 'bukanlibrarymws',
    storageBucket: 'bukanlibrarymws.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6W--xP2YVacymSg2GoL9jtuHPNxEOA0E',
    appId: '1:214009413589:ios:45d120565127a5ffdcc75c',
    messagingSenderId: '214009413589',
    projectId: 'bukanlibrarymws',
    storageBucket: 'bukanlibrarymws.firebasestorage.app',
    iosClientId: '214009413589-snnemn7ak5ev3r1016v3b07tn7g083im.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6W--xP2YVacymSg2GoL9jtuHPNxEOA0E',
    appId: '1:214009413589:ios:45d120565127a5ffdcc75c',
    messagingSenderId: '214009413589',
    projectId: 'bukanlibrarymws',
    storageBucket: 'bukanlibrarymws.firebasestorage.app',
    iosClientId: '214009413589-snnemn7ak5ev3r1016v3b07tn7g083im.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIsUXIz3qf-vqGLNquF_iYJIwkrDxRItc',
    appId: '1:214009413589:web:da45974fa3256369dcc75c',
    messagingSenderId: '214009413589',
    projectId: 'bukanlibrarymws',
    authDomain: 'bukanlibrarymws.firebaseapp.com',
    storageBucket: 'bukanlibrarymws.firebasestorage.app',
  );

}